Moved getOracleTicks to PanopticMath
panoptic-labs/panoptic-v2-core pull request #108
Opened 2024-07-18 18:21 UTC by guil-lambert

This is partly to reduce the bytecode size of PanopticPool.sol, and partly to simplify the calls to PanopticMath when getting the oracle ticks.

- Bytecode size:
  - `main`: `24,532kb`
  - `this branch`: `24,247kb` 
  - = `285b` savings
- PanopticMath external calls in _getOracleTicks:
  - `main` (2):
    - `PanopticMath.computeMedianObservedPrice` and 
    - `PanopticMath.computeInternalMedian`)
  - `this branch` (1):
    - `PanopticMath.getOracleTicks()`

2024-07-19 14:54 UTC, dyedm1 requested changes
Suggested a few improvements, LGTM otherwise

2024-07-19 14:54 UTC, dyedm1 commented on contracts/libraries/PanopticMath.sol
> +        uint256 FAST_ORACLE_CARDINALITY,
We should move these constants into Constants.sol and access them directly or inline them here to reduce overhead.

2024-07-19 14:54 UTC, dyedm1 commented on contracts/PanopticPool.sol
> -        (, uint256 medianData) = PanopticMath.computeInternalMedian(
`computeInternalMedian` is still the most cost-effective option to use here. If you're having contract size issues after making the function internal, you can opt to make it `public` instead (which will perform intra-library calls from `getOracleTicks` inline but otherwise behave similarly to an `external` library function)

2024-07-19 14:54 UTC, dyedm1 commented on contracts/libraries/PanopticMath.sol
> +    ) internal view returns (int24 medianTick, uint256 updatedMedianData) {
See above comment, you may want to consider making this function `public`

2024-07-19 14:54 UTC, dyedm1 commented on test/foundry/core/CollateralTracker.t.sol
> +                (uint256(uint24(currentTick)) << 24) + // add to slot 4
Nice catch!

2024-07-19 14:54 UTC, dyedm1 commented on contracts/libraries/PanopticMath.sol
> +        {
I don't think this scoping does anything?

2024-07-19 14:54 UTC, dyedm1 commented on contracts/libraries/PanopticMath.sol
> +    /// @notice Gets several ticks from Uniswap regarding the underlying pair.
Param natspec?

2024-07-19 14:54 UTC, dyedm1 commented on contracts/PanopticPool.sol
> -    bool internal constant SLOW_ORACLE_UNISWAP_MODE = false;
I don't see any harm in keeping this functionality so we can use it if we want to down the line. I think I remember from our discussion in standup that the reason for removing this was too many parameters being passed into `getOracleTicks` (causing a stack-too-deep (?)), but that becomes a nonissue if you move the constants to `Constants.sol` and access them directly from `getOracleTicks` or inline them as I suggested in another comment.

2024-07-19 14:54 UTC, dyedm1 commented on contracts/libraries/PanopticMath.sol
> +                              UTILITIES
Not sure why this was in the oracle calcs section, good catch lol! I think we can just put this under the generic MATH HELPERS category though.

2024-07-19 14:54 UTC, dyedm1 commented on contracts/PanopticPool.sol
>          medianData = s_miniMedian;
I think you may save some contract size by removing this `getOracleTicks` function and just making `s_miniMedian` public or adding a getter for it so contracts can just call the PanopticMath function (& the UI can call a PanopticHelper wrapper).

2024-07-22 20:31 UTC, flanagansteve reviewed
Henry touched on everything i would mention - can re-review if you pursue his suggestion of retaining the SLOW_ORACLE_UNISWAP_MODE functionality as i imagine the diff will look quite different

2024-07-22 20:31 UTC, flanagansteve commented on contracts/PanopticPool.sol
> -    bool internal constant SLOW_ORACLE_UNISWAP_MODE = false;
I definitely agree that this is worth keeping for now

2024-07-23 01:07 UTC, guil-lambert commented on contracts/libraries/PanopticMath.sol
> +        uint256 FAST_ORACLE_CARDINALITY,
Added all of them to Constants

2024-07-23 01:07 UTC, guil-lambert commented on contracts/PanopticPool.sol
> -        (, uint256 medianData) = PanopticMath.computeInternalMedian(
I added `computeInternalMedian` back

2024-07-23 01:10 UTC, guil-lambert commented on contracts/PanopticPool.sol
> -    bool internal constant SLOW_ORACLE_UNISWAP_MODE = false;
Ok, I've kept it

2024-07-23 01:14 UTC, guil-lambert commented on contracts/PanopticPool.sol
>          medianData = s_miniMedian;
I'll keep this in as is for now, may remove it if bytecode is limiting

2024-07-23 01:20 UTC, merged