feat: withdrawals for accounts with open positions
panoptic-labs/panoptic-v2-core pull request #64
Opened 2024-05-13 18:55 UTC by dyedm1

Added a `withdraw(uint256, address, address, TokenId[])` overload to the standard 4626 interface for users that want to withdraw collateral before closing all their positions. I don't think there's any need for a `redeem` counterpart -- we only use `withdraw(uint256, address, address)` in the UI as of right now.

To accomplish this, I exposed a function, `validateCollateralWithdrawable`, on the PanopticPool. This function wraps a standard internal solvency check (fast oracle tick + slow fallback) with `BP_DECREASE_BUFFER`.

The solvency checking logic could have been moved to a library directly accessible from `CollateralTracker`, but that would add significant gas/call overhead given that the position size/accumulator data is stored in the `PanopticPool`. The former method is cheaper and results in a significantly smaller diff than the latter.

2024-05-13 19:29 UTC, flanagansteve commented on contracts/PanopticPool.sol
> +    function validateCollateralWithdrawable(
Should we consider just making `_validateSolvency` a public method if all this method does is call it and insert in the constant `BP_DECREASE_BUFFER`?

2024-05-13 19:29 UTC, flanagansteve commented on contracts/CollateralTracker.sol
> +            s_poolAssets -= uint128(assets);
I am likely missing something here, but: why are you able to safely cast `assets` down to uint128 if it comes in as a uint256 argument?

2024-05-13 19:37 UTC, dyedm1 commented on contracts/PanopticPool.sol
> +    function validateCollateralWithdrawable(
I wanted to separate concerns here a little to leave the door open for potentially using a different buffer for this down the line. This way, `CollateralTracker` has a standard interface it can use to determine if an account is allowed to withdraw. That interface remains the same even if the underlying mechanism changes.

2024-05-13 19:39 UTC, PeakyCryptos requested changes
Remember to remove the original withdraw function L#511

2024-05-13 19:39 UTC, dyedm1 commented on contracts/CollateralTracker.sol
> +            s_poolAssets -= uint128(assets);
If a user is able to accumulate `>2^128-1` assets worth of shares, the protocol cannot function on that pool either way.

2024-05-13 19:41 UTC, dyedm1 commented
> Remember to remove the original withdraw function L#511

Nah, we still need that one because `withdraw(uint256, address, address, uint256[])` is not ERC4626-compliant.

2024-05-13 19:42 UTC, PeakyCryptos approved these changes

2024-05-20 21:48 UTC, flanagansteve approved these changes

2024-05-20 21:48 UTC, flanagansteve commented on contracts/PanopticPool.sol
> +    function validateCollateralWithdrawable(
Gotcha ok - makes sense!

2024-05-21 13:03 UTC, merged